updated req

diff --git a/ml-cicd-pipeline/.github/workflows/main.yml b/ml-cicd-pipeline/.github/workflows/main.yml
--- a/ml-cicd-pipeline/.github/workflows/main.yml
+++ b/ml-cicd-pipeline/.github/workflows/main.yml
@@ -18,8 +18,9 @@ jobs:
 
     - name: Install dependencies
       run: |
-        pip install -r requirements.txt
-        pip install -U scikit-learn xgboost fastapi uvicorn
+        ls -la
+        echo "Installing dependencies..."
+        pip install -r requirements.txt || (echo "requirements.txt not found" && exit 1)
 
     - name: Run Unit Tests
       run: pytest tests/
